### ISSUE TITLE
Error when registering more than one consumer

### ISSUE THREAD

**Issue by egimenos** [ssut/nestjs-sqs#35]
Hello,

I have an app running correctly consuming from only one queue. Now I'm trying to add an additional queue to the consumers array, but getting this error:

```sh
messaging-service_app  | /app/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:56
messaging-service_app  |             (_a = this.options.consumers) === null || _a === void 0 ? void 0 : _a.forEach((options) => {
messaging-service_app  |                                                                                   ^
messaging-service_app  | TypeError: Cannot read properties of undefined (reading 'meta')
messaging-service_app  |     at /app/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:65:49
messaging-service_app  |     at Array.forEach (<anonymous>)
messaging-service_app  |     at SqsService.<anonymous> (/app/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:56:83)
messaging-service_app  |     at Generator.next (<anonymous>)
messaging-service_app  |     at fulfilled (/app/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:17:58)
messaging-service_app  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
messaging-service_app  |   prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
```
`consumer.module.ts`

```ts
@Module({
  imports: [
    SqsModule.registerAsync({
      useFactory: () => {
        return {
          consumers: consumerConfig,
          producers: producerConfig,
        };
      },
    }),
...
```
The consumerConfig object is build like that:

```ts
export const consumerConfig: SqsConsumerOptions[] = [
  {
    name: 'email_delivery_request',
    queueUrl: ' http://localhost:4566/000000000000/email_delivery_request',
    region,
  },
  {
    name: 'email_status_change',
    queueUrl: 'http://localhost:4566/000000000000/email_status_change',
    region,
  },
];
```
Any idea what might be happening? This exact setup is working fine if the consumerConfig array has only one element.

Thanks in advance.

**Comment by adamjq** [comment]
@egimenos I'm getting the same error after following the docs. Could you share you working code?

**Comment by HeavenH** [comment]
can help me configure with localstack? don't work me

**Comment by edgahan** [comment]
I had the above error but my issue was for the queue name I was not providing the full arn name, e.g. `arn:aws:sqs:us-east-1:3xxxxx8:name`
