### ISSUE TITLE
@ssut/nestjs-sqs Compatibility Concern with NestJs V8, V9 & V10

### ISSUE THREAD

**Issue by avinashiitb** [ssut/nestjs-sqs#60]
**SQS Consumer Compatibility Concern**

I am trying to implement SQS consumer in a NestJs project using the `@ssut/nestjs-sqs` library (version 1.3.0 and 2.1.0). However, I've encountered a major concern with compatibility issues with different Nest.js versions.

Here are my observations:

| Nest.js Version | @ssut/nestjs-sqs Version | Working |
|-----------------|-------------------------|---------|
| V8.0.0          | V1.3.0                  | No      |
| V8.0.0          | V2.1.0                  | No      |
| V9.0.0          | V1.3.0                  | Yes     |
| V9.0.0          | V2.1.0                  | No      |
| V10.0.0         | V1.3.0                  | No      |
| V10.0.0         | V2.1.0                  | No      |

I am facing issues with `@ssut/nestjs-sqs` version 1.3.0 and 2.1.0 in Nest.js versions 8.0.0, 9.0.0, and 10.0.0.
I am getting different -different error for different versions for the same code

****Note** :- I have used the code in each version to test the compatibility**

| Nest.js Version | @ssut/nestjs-sqs Version |
|-----------------|-------------------------|
| V8.0.0          | V1.3.0                  |
```
/Users/avinash.anshu/Project/Practice/sqs-v8/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:56
            (_a = this.options.consumers) === null || _a === void 0 ? void 0 : _a.forEach((options) => {
                                                                                  ^
TypeError: Cannot read properties of undefined (reading 'meta')
    at /Users/avinash.anshu/Project/Practice/sqs-v8/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:65:49
    at Array.forEach (<anonymous>)
    at SqsService.<anonymous> (/Users/avinash.anshu/Project/Practice/sqs-v8/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:56:83)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/avinash.anshu/Project/Practice/sqs-v8/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:17:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
  ```
  
| Nest.js Version | @ssut/nestjs-sqs Version |
|-----------------|-------------------------|
| V8.0.0          | V2.1.0                  |
```
/Users/avinash.anshu/Project/Practice/sqs-v8-latest/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:55
            (_b = this.options.consumers) === null || _b === void 0 ? void 0 : _b.forEach((options) => {
                                                                                  ^
TypeError: Cannot read properties of undefined (reading 'meta')
    at /Users/avinash.anshu/Project/Practice/sqs-v8-latest/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:64:49
    at Array.forEach (<anonymous>)
    at SqsService.<anonymous> (/Users/avinash.anshu/Project/Practice/sqs-v8-latest/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:55:83)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/avinash.anshu/Project/Practice/sqs-v8-latest/node_modules/@ssut/nestjs-sqs/dist/sqs.service.js:17:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

| Nest.js Version | @ssut/nestjs-sqs Version |
|-----------------|-------------------------|
| V9.0.0          | V2.1.0                  |
```
(node:33736) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

/Users/avinash.anshu/Project/Practice/sqs-v9-latest/node_modules/sqs-consumer/dist/errors.js:40
    const sqsError = new SQSError(message);
                     ^
SQSError: SQS receive message failed: The security token included in the request is invalid.
    at toSQSError (/Users/avinash.anshu/Project/Practice/sqs-v9-latest/node_modules/sqs-consumer/dist/errors.js:40:22)
    at Consumer.receiveMessage (/Users/avinash.anshu/Project/Practice/sqs-v9-latest/node_modules/sqs-consumer/dist/consumer.js:173:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
   ```
   
   | Nest.js Version | @ssut/nestjs-sqs Version |
|-----------------|-------------------------|
| V10.0.0          | V1.3.0                  |
```
[Nest] 33753  - 07/27/2023, 10:05:23 AM   ERROR [ExceptionHandler] Cannot read properties of undefined (reading 'values')
TypeError: Cannot read properties of undefined (reading 'values')
    at /Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/@nestjs-plus/discovery/src/discovery.service.ts:68:50
    at arrayMap (/Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/lodash/lodash.js:653:23)
    at map (/Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/lodash/lodash.js:9622:14)
    at Function.flatMap (/Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/lodash/lodash.js:9325:26)
    at new DiscoveryService (/Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/@nestjs-plus/discovery/src/discovery.service.ts:67:7)
    at Injector.instantiateClass (/Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/@nestjs/core/injector/injector.js:65:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Injector.resolveConstructorParams (/Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/@nestjs/core/injector/injector.js:144:24)
    at Injector.loadInstance (/Users/avinash.anshu/Project/Practice/sqs-v10/node_modules/@nestjs/core/injector/injector.js:70:13)
```

   | Nest.js Version | @ssut/nestjs-sqs Version |
|-----------------|-------------------------|
| V10.0.0          | V2.1.0                  |
```
(node:33776) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

/Users/avinash.anshu/Project/Practice/sqs-v10-latest/node_modules/sqs-consumer/dist/errors.js:40
    const sqsError = new SQSError(message);
                     ^
SQSError: SQS receive message failed: The security token included in the request is invalid.
    at toSQSError (/Users/avinash.anshu/Project/Practice/sqs-v10-latest/node_modules/sqs-consumer/dist/errors.js:40:22)
    at Consumer.receiveMessage (/Users/avinash.anshu/Project/Practice/sqs-v10-latest/node_modules/sqs-consumer/dist/consumer.js:173:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ssut** [comment]
Do you still have the same issue with v2.2.0? Please reopen the PR if it does.
